#app_folder
#app_key: "fjjw9s6qi80z6yt"
#app_secret: <%= ENV["APP_SECRET"] %>
#access_token: "plddvn6upswxbgvj"
#access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"]%>
#user_id: "24650941"
#access_type: "app_folder"

#dropbox - public
app_key: "pxu7nvi8g9vfffe"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "owxjhbk4f1yd5pl4"
access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"]%>
user_id: "24650941"
access_type: "dropbox"